[package]
name = "celosignerembed"
version = "0.1.0"
authors = ["Marek Olszewski <m@celo.org>"]
edition = "2018"

[dependencies]

[lib]
name = "celosignerembed"
crate-type = ["staticlib"]
lto = true
opt-level = "s"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
